export const BROWSE_SONGS = [
  // Telugu Songs
  {
    id: "br-tel-1",
    title: "అడవి చెట్ల నడుమ",
    artist: "O Yaathrikudaa",
    album: "Worship Sessions",
    genre: "Rock",
    duration: "4:15",
    durationSec: 255,
    coverUrl: "/worship_forest.png",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    releaseYear: 2024,
    bpm: 78,
    plays: 2150000,
    language: "telugu",
    startingLetter: "అ"
  },
  {
    id: "br-tel-2",
    title: "ఆరాధన నీకే",
    artist: "Praise Choir",
    album: "Eternal Worship",
    genre: "Pop",
    duration: "5:30",
    durationSec: 330,
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    releaseYear: 2023,
    bpm: 90,
    plays: 89000,
    language: "telugu",
    startingLetter: "ఆ"
  },
  {
    id: "br-tel-3",
    title: "కరుణామయుడా",
    artist: "Bro. John",
    album: "Grace Flows",
    genre: "Lo-Fi",
    duration: "3:45",
    durationSec: 225,
    coverUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    releaseYear: 2024,
    bpm: 72,
    plays: 120000,
    language: "telugu",
    startingLetter: "క"
  },
  {
    id: "br-tel-4",
    title: "దేవుడే నా వెలుగు",
    artist: "Prarthana Group",
    album: "Light of Life",
    genre: "Synthwave",
    duration: "6:12",
    durationSec: 372,
    coverUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    releaseYear: 2022,
    bpm: 110,
    plays: 45000,
    language: "telugu",
    startingLetter: "ద"
  },
  {
    id: "br-tel-5",
    title: "యెహోవా నా కాపరి",
    artist: "David's Harp",
    album: "Psalms of Praise",
    genre: "Rock",
    duration: "4:55",
    durationSec: 295,
    coverUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    releaseYear: 2021,
    bpm: 82,
    plays: 98000,
    language: "telugu",
    startingLetter: "య"
  },
  {
    id: "br-tel-6",
    title: "స్తుతియించెదన్",
    artist: "Emmanuel Band",
    album: "Glorious Path",
    genre: "Pop",
    duration: "5:10",
    durationSec: 310,
    coverUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    releaseYear: 2023,
    bpm: 118,
    plays: 154000,
    language: "telugu",
    startingLetter: "స"
  },
  {
    id: "br-tel-7",
    title: "హోసన్నా",
    artist: "Zion Singers",
    album: "Hosanna in High",
    genre: "Lo-Fi",
    duration: "4:28",
    durationSec: 268,
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    releaseYear: 2024,
    bpm: 68,
    plays: 320000,
    language: "telugu",
    startingLetter: "హ"
  },

  // English Songs
  {
    id: "br-eng-1",
    title: "Amazing Grace",
    artist: "John Newton",
    album: "Hymns of Faith",
    genre: "Lo-Fi",
    duration: "4:02",
    durationSec: 242,
    coverUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    releaseYear: 2020,
    bpm: 68,
    plays: 954000,
    language: "english",
    startingLetter: "A"
  },
  {
    id: "br-eng-2",
    title: "Cornerstone",
    artist: "Hillsong Worship",
    album: "Cornerstone Live",
    genre: "Rock",
    duration: "6:25",
    durationSec: 385,
    coverUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    releaseYear: 2021,
    bpm: 74,
    plays: 840000,
    language: "english",
    startingLetter: "C"
  },
  {
    id: "br-eng-3",
    title: "Goodness of God",
    artist: "Bethel Music",
    album: "Victory",
    genre: "Pop",
    duration: "5:02",
    durationSec: 302,
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    releaseYear: 2019,
    bpm: 63,
    plays: 1245000,
    language: "english",
    startingLetter: "G"
  },
  {
    id: "br-eng-4",
    title: "How Great Is Our God",
    artist: "Chris Tomlin",
    album: "Arriving",
    genre: "Rock",
    duration: "4:45",
    durationSec: 285,
    coverUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    releaseYear: 2020,
    bpm: 78,
    plays: 1750000,
    language: "english",
    startingLetter: "H"
  },
  {
    id: "br-eng-5",
    title: "In Christ Alone",
    artist: "Keith & Kristyn Getty",
    album: "In Christ Alone",
    genre: "Lo-Fi",
    duration: "5:12",
    durationSec: 312,
    coverUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    releaseYear: 2021,
    bpm: 70,
    plays: 630000,
    language: "english",
    startingLetter: "I"
  },
  {
    id: "br-eng-6",
    title: "Reckless Love",
    artist: "Cory Asbury",
    album: "Reckless Love Album",
    genre: "Pop",
    duration: "5:33",
    durationSec: 333,
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    releaseYear: 2018,
    bpm: 83,
    plays: 1420000,
    language: "english",
    startingLetter: "R"
  },
  {
    id: "br-eng-7",
    title: "Ten Thousand Reasons",
    artist: "Matt Redman",
    album: "10,000 Reasons Live",
    genre: "Synthwave",
    duration: "5:41",
    durationSec: 341,
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    releaseYear: 2011,
    bpm: 73,
    plays: 1890000,
    language: "english",
    startingLetter: "T"
  },
  {
    id: "br-eng-8",
    title: "Way Maker",
    artist: "Sinach",
    album: "Way Maker Single",
    genre: "Synthwave",
    duration: "6:08",
    durationSec: 368,
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    releaseYear: 2015,
    bpm: 66,
    plays: 2310000,
    language: "english",
    startingLetter: "W"
  }
];
